port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: warning
external-controller: 0.0.0.0:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - https://1.1.1.1/dns-query
    - https://dns.cloudflare.com/dns-query


proxy-groups:
  - name: "auto"
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 100


rule-providers:
  iran:
    type: http
    behavior: classical
    url: "https://github.com/chiroots/iran-hosted-domains/releases/latest/download/clash_rules.yaml"
    path: ./ruleset/iran.yaml
    interval: 432000


rules:
  - DOMAIN-KEYWORD,*.ir,DIRECT
  - RULE-SET,iran,DIRECT
  - MATCH,auto

